version: '3'

services:
  graph-db:
    image: neo4j:latest
    container_name: invana-neo4j-instance-1
    restart: always

  gremlin-server:
    image: tinkerpop/gremlin-server
    container_name: invana-neo4j-gremlin-server-1
    restart: always
    environment:
      - GREMLIN_SERVER_URL=ws://graph-db:8182/gremlin
    depends_on:
      - "graph-db"

  invana-engine:
    image: invanalabs/invana-engine
    container_name: invana-neo4j-invana-engine-1
    restart: always
    ports:
      - "8200:8200"
    environment:
      - GREMLIN_SERVER_URL=ws://gremlin-server:8182/gremlin
    depends_on:
      - "gremlin-server"

  invana-studio:
    image: invanalabs/invana-studio
    container_name: invana-neo4j-invana-studio-1
    ports:
      - "8888:8888"

