version: '3'

services:
  graph-db:
    image: docker.io/janusgraph/janusgraph:latest
    container_name: janusgraph-instance-2
    restart: always
    ports:
      - "8182:8182"
    volumes:
      # bind mounts for configs; use read only so not overridden by environment variables
      - "./conf:/etc/opt/janusgraph/:ro"
    networks:
      - jce-network-1

  cassandra:
    image: cassandra:3
    container_name: janusgraph-cassandra-2
    ports:
      - "9042:9042"
      - "9160:9160"
    networks:
      - jce-network-1

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: janusgraph-elasticsearch-2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - "network.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "cluster.name=docker-cluster"
      - "xpack.security.enabled=false"
      - "discovery.zen.minimum_master_nodes=1"
    ports:
      - "9200:9200"
    networks:
      - jce-network-1

networks:
  jce-network-1: